[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.12", features = [
  "sqlx-postgres",
  "runtime-actix-native-tls",
] }

[lib]
name = "shared"
path = "lib.rs"
